#!/bin/bash
echo "=== Monitoring SGG ==="
echo "Date : $(date)"
echo ""
echo "Backend :"
curl -s http://localhost:3000/api/test > /dev/null 2>&1 && echo "✅ API en ligne" || echo "❌ API hors ligne"
echo ""
echo "Frontend :"
curl -s http://localhost/ > /dev/null 2>&1 && echo "✅ Frontend accessible" || echo "❌ Frontend inaccessible"
echo ""
echo "Base de données :"
sudo -u postgres psql -d sgg_db -c "SELECT 1;" > /dev/null 2>&1 && echo "✅ BDD accessible" || echo "❌ BDD inaccessible"
echo ""
echo "Statistiques :"
sudo -u postgres psql -d sgg_db -t -c "SELECT COUNT(*) || ' actions' FROM actions;"
sudo -u postgres psql -d sgg_db -t -c "SELECT COUNT(*) || ' utilisateurs actifs' FROM users WHERE is_active = true;"
